export { default as About } from './common/About.jsx'
export { default as AnimatedStat } from './ui/AnimatedStat.jsx'
export { default as Footer } from './common/Footer.jsx'
export { default as Hero } from './common/Hero.jsx'
export { default as Navbar } from './common/Navbar.jsx'
export { default as Skills } from './common/Skills.jsx'
export { default as SkillProgress } from './ui/SkillProgress.jsx'
export { default as TechBadge } from './ui/TechBadge.jsx'
